apiVersion: v1
kind: Namespace
metadata:
  name: josh-tok-com
---
apiVersion: v1
kind: Service
metadata:
  name: josh-tok-com
spec:
  ports:
  - port: 8083
    targetPort: 80
  selector:
    app: josh-tok-com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: josh-tok-com
spec:
  selector:
    matchLabels:
      app: josh-tok-com
  replicas: 1
  template:
    metadata:
      labels:
        app: josh-tok-com
    spec:
      containers:
      - name: josh-tok-com
        image: ""
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: josh-tok-com-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
  - hosts:
    - josh-tok.com
    secretName: josh-tok-com-tls
  rules:
  - host: josh-tok.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: josh-tok-com
            port:
              number: 80
